version: "3.7"
services:
  rails_chat_prod:
      build:
        context: ./rails-chat-service
        target: production
      env_file:
        - ./rails-chat-service/config/envfiles/production.env
      ports:
        - 3000:3000
      depends_on:
        - db
      restart: always
      links:
        - db
  go_chat_prod:
      build:
        context: ./go-chat-service
        target: production
      env_file:
        - ./go-chat-service/config/production.env
      ports:
        - 8000:8000
      depends_on:
        - db
      restart: always
      links:
        - db
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./rails-chat-service/config/envfiles/production.env
    ports: 
      - '3307:3306'
    volumes:
      - ~/mysql_data/chat_system_prod:/var/lib/mysql
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01_prod:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02_prod:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
volumes:
  data01_prod:
    driver: local
  data02_prod:
    driver: local
networks:
  elastic:
    driver: bridge    