version: "3.7"
services:
  rails_chat_prod:
      build:
        context: ./rails-chat-service
        target: production
      env_file:
        - ./rails-chat-service/config/envfiles/production.env
      ports:
        - 3000:3000
      depends_on:
        - db
      restart: always
      links:
        - db
  go_chat_prod:
      build:
        context: ./go-chat-service
        target: production
      env_file:
        - ./go-chat-service/config/production.env
      ports:
        - 8000:8000
      depends_on:
        - db
      restart: always
      links:
        - db
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./rails-chat-service/config/envfiles/production.env
    ports: 
      - '3307:3306'
    volumes:
      - ~/mysql_data/chat_system_prod:/var/lib/mysql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    volumes:
      - data_prod:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
volumes:
  data_prod:
    driver: local