version: "3.7"
services:
  rails_chat_dev:
      build:
        context: ./rails-chat-service
        target: development
      env_file:
        - ./rails-chat-service/config/envfiles/development.env
      ports:
        - 3000:3000
      depends_on:
        - db
      restart: always
      links:
        - db    
      volumes: 
        - "./rails-chat-service:/app"
        - /app/tmp/
  go_chat_dev:
      build:
        context: ./go-chat-service
        target: development
      env_file:
        - ./go-chat-service/config/development.env
      ports:
        - 8000:8000
      depends_on:
        - db
      restart: always
      links:
        - db    
      volumes: 
        - "./go-chat-service:/app"
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./rails-chat-service/config/envfiles/development.env
    ports: 
      - '3307:3306'
    volumes:
      - ~/mysql_data/chat_system_dev:/var/lib/mysql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    volumes:
      - data_dev:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
volumes:
  data_dev:
    driver: local